// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBAf2fbfZUBUHTq3VdCgeVANLwmNn7fu2U',
    appId: '1:936981766823:web:9f857b02c589d375d2f182',
    messagingSenderId: '936981766823',
    projectId: 'reelrave-3d6db',
    authDomain: 'reelrave-3d6db.firebaseapp.com',
    storageBucket: 'reelrave-3d6db.appspot.com',
    measurementId: 'G-DMVM8134D7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBWlMxxuKgPLLatkbaqFOoNbhbuqkdav90',
    appId: '1:936981766823:android:68796c6a85540404d2f182',
    messagingSenderId: '936981766823',
    projectId: 'reelrave-3d6db',
    storageBucket: 'reelrave-3d6db.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPPTVqEZs5k-VFuIfh_Vo0PRowY_B4mBI',
    appId: '1:936981766823:ios:07d66f48c58da626d2f182',
    messagingSenderId: '936981766823',
    projectId: 'reelrave-3d6db',
    storageBucket: 'reelrave-3d6db.appspot.com',
    iosBundleId: 'com.example.reelRave',
  );
}
